version: '3.8'

volumes:
  postresql_data:


x-base:
  &base
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432

services:
  web:
    <<: *base
    build: .
    command: /bin/sh -c 'alembic upgrade head && uvicorn server:app --host "0.0.0.0" --port 8000 --reload'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
  db:
    <<: *base
    image: postgres
    volumes:
      - postresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
