"""initial migration

Revision ID: 947a07fb6f18
Revises: 
Create Date: 2023-04-15 21:47:37.936879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947a07fb6f18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table('recipes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('ingredients', sa.String(), nullable=True),
                    sa.Column('instructions', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))

    op.create_table('recipe_tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('recipe_id', sa.Integer(), nullable=False),
                    sa.Column('tag_id', sa.Integer(), nullable=False),
                    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
